### ISSUE TITLE
Calibration utilities

### ISSUE THREAD

**Issue by JakeHartnell** [CommonGarden/grow.js#129]
As a grower, I want utilities to calibrate a sensor with multiple known values. For example, using an Analog pH sensor and three reference solutions (acid, neutral, alkaline).

**Comment by JakeHartnell** [comment]
Started in the [0.4 branch](https://github.com/CommonGarden/Grow.js/tree/0.4).

**Comment by catbarph** [comment]
Another use-case I'm facing with analog sensors is with the eTape liquid level sensor. 
The interfacing electronics can be tuned to an extent (i.e. dampening/shifting a signal) but sometimes a better approach is with software (i.e. remapping values - perhaps dynamically). 
eTape also features a reference path for temperature compensation, so this would be a great opportunity to do some two-point calibration functions, before we get to the three-point! @JakeHartnell
