### ISSUE TITLE
Sensor polling logic

### ISSUE THREAD

**Issue by catbarph** [CommonGarden/grow.js#133]
While many environmental sensors can/should be polled & logged on a regular basis (e.g. ambient air temp), others need basic conditions to be met before they'll produce usable readings.

e.g. for aqueous sensors in a "sensor pipe" configuration, the pump needs to be activated and given enough time to homogenize (or not) the batch before sensors are polled.

**Comment by JakeHartnell** [comment]
Updated the bioreactor example to help address this: https://github.com/CommonGarden/Grow.js/commit/b94d0cf2a6600ff3bd2d569ccbb7e3e390d5f92f

Want to test it out? It should log data every minute by default. This is the relevant bit:
```javascript
        var interval = this.get('interval');

        emit_data = setInterval(()=> {
          this.temp_data();
          this.hum_data();
          this.light_data();
          this.air_pressure_data();
          this.water_level_data();
          // Turn pump on to read aqueous sensors.
          this.water_pump_on();
          setTimeout(()=> {
            this.ph_data();
            this.ec_data();
            this.water_temp_data();
            setTimeout(()=> {
              this.do_data();
              // Turn water pump off.
              this.water_pump_off();
            }, 1000);
          }, 30000)
        }, interval > 60000 ? interval: 60000);
```
