### ISSUE TITLE
Connecting over SSL

### ISSUE THREAD

**Issue by JakeHartnell** [CommonGarden/grow.js#20]
So, I've got an instance of Grow-IoT at: https://grow.commongarden.org

Getting this error: Network error: wss://grow.commongarden.org:443/websocket: Hostname/IP doesn't match certificate's altnames: "Host: grow.commongarden.org. is not in the cert's altnames: DNS:*.meteor.com, DNS:meteor.com"

I'm hosting on Meteor galaxy...  I've tried to include the altnames with my openssl config file:

```
[req]
distinguished_name = req_distinguished_name
req_extensions = v3_req

[req_distinguished_name]
countryName = US
stateOrProvinceName = CA
localityName = Berkeley
organizationalUnitName  = Organizational Unit Name (eg, section)
organizationalUnitName_default  = Domain Control Validated
commonName = Common Garden
commonName_max  = 64

[ v3_req ]
# Extensions to add to a certificate request
basicConstraints = CA:FALSE
keyUsage = nonRepudiation, digitalSignature, keyEncipherment
subjectAltName = @alt_names

[alt_names]
DNS.1 = grow.commongarden.com
DNS.2 = *.meteor.com
DNS.3 = meteor.com

```

But no luck. Sure the application is running in the browser, but our devices can't connect to our instance over SSL yet.

@mitar any thoughts on what I'm doing wrong?

**Comment by mitar** [comment]
What was the solution?

**Comment by mitar** [comment]
I would guess they use SNI to provide SSL certificates. Maybe the client libraries does not support it?

**Comment by JakeHartnell** [comment]
Works! Thanks @mitar for the help.
